version = 0.1
[default.deploy.parameters]
stack_name = "sam-api-testing"
resolve_s3 = true
s3_prefix = "sam-api-testing"
region = "ap-northeast-1"
profile = "cli-user"
capabilities = "CAPABILITY_IAM"
image_repositories = []
